# Generated by Django 5.2.7 on 2025-10-19 12:26

import django.core.validators
import fr_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageAndPredict',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('unique_id', models.CharField(default=fr_api.models.generate_unique_id, editable=False, max_length=10, verbose_name='Identifiant unique')),
                ('img1', models.ImageField(upload_to="/temp", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message="Format d'image non supporté. Utilisez JPG, PNG, GIF ou WEBP.")], verbose_name='Image 1')),
                ('img2', models.ImageField(upload_to="/temp", validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message="Format d'image non supporté. Utilisez JPG, PNG, GIF ou WEBP.")], verbose_name='Image 2')),
                ('prediction', models.CharField(null = True, editable=False, max_length=255, verbose_name='Prédiction')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-date_upload'],
            },
        ),
    ]
