# Generated by Django 5.2.7 on 2025-12-29 02:27

import django.core.validators
import fr_api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='img1_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='img2_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='rightprediction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Prédiction corriger par l'utilisateur"),
        ),
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='selected_model',
            field=models.IntegerField(default=0, verbose_name='Model choisi'),
        ),
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de session'),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='img1',
            field=models.ImageField(upload_to='temp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message="Format d'image non supporté. Utilisez JPG, PNG, GIF ou WEBP."), fr_api.models.validate_file_size], verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='img2',
            field=models.ImageField(upload_to='temp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message="Format d'image non supporté. Utilisez JPG, PNG, GIF ou WEBP."), fr_api.models.validate_file_size], verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='prediction',
            field=models.CharField(max_length=255, null=True, verbose_name='Prédiction'),
        ),
    ]
