# Generated by Django 5.2.7 on 2025-12-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0002_uploadimageandpredict_img1_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimageandpredict',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='uploadimageandpredict',
            name='img2',
        ),
    ]
