# Generated by Django 5.2.7 on 2025-10-19 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0002_alter_uploadimageandpredict_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='prediction1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Corriger la prédiction'),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
