# Generated by Django 5.2.7 on 2025-10-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0003_uploadimageandpredict_prediction1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimageandpredict',
            old_name='prediction1',
            new_name='rightprediction',
        ),
    ]
