# Generated by Django 5.2.7 on 2026-1-7 23:24

import django.core.validators
import fr_api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0003_remove_uploadimageandpredict_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='feedback',
            field=models.FloatField(blank=True, null=True, editable=True, default= 0.0, verbose_name = "Feedback"),
        )
        )
    ]
