# Generated by Django 5.2.7 on 2025-10-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0004_rename_prediction1_uploadimageandpredict_rightprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de session'),
        ),
    ]
