# Generated by Django 5.2.7 on 2025-12-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0005_uploadimageandpredict_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimageandpredict',
            name='selected_model',
            field=models.CharField(default=0, max_length=255, verbose_name='Model choisi'),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='prediction',
            field=models.CharField(max_length=255, null=True, verbose_name='Prédiction'),
        ),
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='rightprediction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Prédiction corriger par l'utilisateur"),
        ),
    ]
