# Generated by Django 5.2.7 on 2025-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_api', '0007_alter_uploadimageandpredict_selected_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimageandpredict',
            name='selected_model',
            field=models.IntegerField(default=0, verbose_name='Model choisi'),
        ),
    ]
